version: '3.8'

services:
  web:
    build: .
    image: myapp:${TAG}
    ports:
      - "8080:8000"
    networks:
      - app_net
    environment:
      - DJANGO_SETTINGS_MODULE=coolsite.settings
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    networks:
      - app_net
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./etc/loki/local-config.yaml:/etc/loki/local-config.yaml

    environment:
      - LOKI_SCHEMA_CONFIG_CONFIGS_0_FROM=2020-10-24
      - LOKI_SCHEMA_CONFIG_CONFIGS_0_STORE=boltdb-shipper
      - LOKI_SCHEMA_CONFIG_CONFIGS_0_OBJECT_STORE=filesystem
      - LOKI_SCHEMA_CONFIG_CONFIGS_0_SCHEMA=v11
      - LOKI_SCHEMA_CONFIG_CONFIGS_0_INDEX_PREFIX=index_
      - LOKI_SCHEMA_CONFIG_CONFIGS_0_INDEX_PERIOD=24h

  grafana:
    image: grafana/grafana:8.0.6
    ports:
      - "3000:3000"
    networks:
      - app_net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

networks:
  app_net:
    driver: bridge
