version: '3.8'

services:
  web:
    build: .
    image: myapp:${TAG}
    ports:
      - "8080:8000"
    networks:
      - app_net
    environment:
      - DJANGO_SETTINGS_MODULE=coolsite.settings
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    networks:
      - app_net
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./etc/loki/local-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    networks:
      - app_net
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - app_net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.0.6
    ports:
      - "3000:3000"
    networks:
      - app_net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

networks:
  app_net:
    driver: bridge
